Add Delete Button
Anita77777/capstone-project pull request #14
Opened 2022-05-23 15:52 UTC by Anita77777

2022-05-23 18:58 UTC, doemser requested changes
Good Work! :)

Try to handle the bookmarked useStates you use in Form.js within your useStore as well. Remember how we checked a todo in our todo-app? Checking a todo is pretty similar to bookmarking it.

2022-05-23 18:58 UTC, doemser commented on src/components/useStore/useStore.js
>  );
good job! you could call this function "deleteBook" because it always deletes one book.

2022-05-24 07:50 UTC, doemser commented
In Slack you wrote:
"Thanks for the review. The bookmarks are another branch wich were already approved. Should I just apply the changes you requested regarding the bookmarks on this branch?"

I see that there is a branch that was about the bookmark feature and was already merged. The changes I requested are regarding another feature, so you could go for a refactoring of your bookmark functionality in a separate PR to keep working on one feature at once.

As long as you promise to refactor it and change the function naming, I will approve your PR here and wait for your next one where you refactor it :P

2022-05-24 07:53 UTC, Anita77777 commented
I changed the function name and will immediately work on the refactoring of the bookmark buttons

2022-05-24 08:10 UTC, doemser approved these changes
:)

2022-05-24 10:07 UTC, merged