add routing
Anita77777/capstone-project pull request #20
Opened 2022-05-31 11:41 UTC by Anita77777

2022-05-31 21:02 UTC, irenepapaspyratos requested changes

2022-05-31 21:02 UTC, irenepapaspyratos commented on src/components/Navbar/Navbar.js
> +}
As I understood, a footer is normally used to display final information at the end of a page (foot...below..).
So first, putting a footer at the top is strange and second there should be info like impressum etc. (things, you don't want to see always but on scrollToEnd).
I think, what you want is a \<nav> . Maybe wrapped in a \<header>, but definitive a \<nav>.

2022-05-31 21:15 UTC, Anita77777 commented on src/components/Navbar/Navbar.js
> +}
Yeah the footer will be at the bottom as soon I style the page, next step. If you add a card the footer sludes down, but as I said the stylinf of the whole app is my next step after this PR

2022-05-31 21:44 UTC, irenepapaspyratos commented on src/components/Navbar/Navbar.js
> +}
Ok, but...: nevertheless - top or bottom - what you have been building is a \<nav>, not a \<footer>. I strongly suggest to change that, as it is semantically wrong. Sorry...😔

2022-05-31 21:55 UTC, irenepapaspyratos requested changes

2022-05-31 21:55 UTC, irenepapaspyratos commented on src/components/Footer/Footer.js
> +export default function Footer() {
Change back to Navbar

2022-05-31 21:55 UTC, irenepapaspyratos commented on src/components/Footer/Footer.js
>  		<footer>
Change \<footer> and \</footer> to \<nav> and \</nav>

2022-05-31 21:55 UTC, irenepapaspyratos commented on src/components/Layout.js
Change Footer back to Navbar

2022-05-31 21:55 UTC, irenepapaspyratos commented on src/components/Layout.js
>  			<main>{children}</main>
Change \<Footer /> back to \<Navbar />

2022-06-01 07:05 UTC, irenepapaspyratos approved these changes

2022-06-01 07:05 UTC, irenepapaspyratos commented
Very well done!! :)

2022-06-01 07:33 UTC, merged